# Generated by Django 5.0 on 2025-11-20 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('COMUN', 'Común')], default='COMUN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='ESTACION_METEOROLOGICA',
            fields=[
                ('codigo_nacional', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_estacion', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('altura', models.IntegerField()),
            ],
            options={
                'db_table': 'ESTACION_METEOROLOGICA',
            },
        ),
        migrations.CreateModel(
            name='OFICINA',
            fields=[
                ('id_oficina', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('georeferencia', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'OFICINA',
            },
        ),
        migrations.CreateModel(
            name='SENSOR',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'SENSOR',
            },
        ),
        migrations.CreateModel(
            name='THERMOSTATO',
            fields=[
                ('id_thermostato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'THERMOSTATO',
            },
        ),
        migrations.CreateModel(
            name='TIPO_ZONA',
            fields=[
                ('id_tipozona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TIPO_ZONA',
            },
        ),
        migrations.CreateModel(
            name='MEDICION_METEOROLOGICA',
            fields=[
                ('id_medicionmeteorologica', models.AutoField(primary_key=True, serialize=False)),
                ('momento', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('temperatura_minima_12h', models.FloatField()),
                ('temperatura_maxima_12h', models.FloatField()),
                ('humedad_relativa', models.FloatField()),
                ('codigo_nacional', models.ForeignKey(db_column='codigo_nacional', on_delete=django.db.models.deletion.CASCADE, to='core.estacion_meteorologica')),
            ],
            options={
                'db_table': 'MEDICION_METEOROLOGICA',
            },
        ),
        migrations.CreateModel(
            name='OFICINA_ESTACION',
            fields=[
                ('id_oficinaestacion', models.AutoField(primary_key=True, serialize=False)),
                ('principal', models.CharField(max_length=100)),
                ('distancia_km', models.IntegerField()),
                ('codigo_nacional', models.ForeignKey(db_column='codigo_nacional', on_delete=django.db.models.deletion.CASCADE, to='core.estacion_meteorologica')),
                ('id_oficina', models.ForeignKey(db_column='id_oficina', on_delete=django.db.models.deletion.CASCADE, to='core.oficina')),
            ],
            options={
                'db_table': 'OFICINA_ESTACION',
            },
        ),
        migrations.CreateModel(
            name='POSICION_SOLAR',
            fields=[
                ('id_posicionsolar', models.AutoField(primary_key=True, serialize=False)),
                ('momento', models.DateTimeField()),
                ('elevacion', models.FloatField()),
                ('azimut', models.FloatField()),
                ('codigo_nacional', models.ForeignKey(db_column='codigo_nacional', on_delete=django.db.models.deletion.CASCADE, to='core.estacion_meteorologica')),
            ],
            options={
                'db_table': 'POSICION_SOLAR',
            },
        ),
        migrations.CreateModel(
            name='MEDICION_SENSOR',
            fields=[
                ('id_medicionsensor', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('unidad', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('id_sensor', models.ForeignKey(db_column='id_sensor', on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
            ],
            options={
                'db_table': 'MEDICION_SENSOR',
            },
        ),
        migrations.CreateModel(
            name='MEDICION_THERMOSTATO',
            fields=[
                ('id_medicionthermostato', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('unidad', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('id_thermostato', models.ForeignKey(db_column='id_thermostato', on_delete=django.db.models.deletion.CASCADE, to='core.thermostato')),
            ],
            options={
                'db_table': 'MEDICION_THERMOSTATO',
            },
        ),
        migrations.CreateModel(
            name='ZONA',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('orientacion', models.CharField(max_length=100)),
                ('superficie_m3', models.IntegerField()),
                ('cantidad_equipos', models.IntegerField()),
                ('forma_svg', models.TextField()),
                ('id_oficina', models.ForeignKey(db_column='id_oficina', on_delete=django.db.models.deletion.CASCADE, to='core.oficina')),
                ('id_tipozona', models.ForeignKey(db_column='id_tipozona', on_delete=django.db.models.deletion.CASCADE, to='core.tipo_zona')),
            ],
            options={
                'db_table': 'ZONA',
            },
        ),
        migrations.AddField(
            model_name='thermostato',
            name='id_zona',
            field=models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.CASCADE, to='core.zona'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='id_zona',
            field=models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.CASCADE, to='core.zona'),
        ),
        migrations.CreateModel(
            name='MATERIAL_ZONA',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_m2', models.IntegerField()),
                ('id_zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.CASCADE, to='core.zona')),
            ],
            options={
                'db_table': 'MATERIAL_ZONA',
            },
        ),
    ]
